package hired

//Auto generated code for hiring workers.
//DO NOT EDIT THIS FILE.
import worker "github.com/herb-go/worker"

func init() {
	//Worker "hired.TOMLAppKey"
	//You can add Introduction by add comment in form WORKER(TOMLAppKey):Introduction
	worker.Hire("hired.TOMLAppKey", &TOMLAppKey)

	//Worker "hired.TOMLAppKeySigner"
	//You can add Introduction by add comment in form WORKER(TOMLAppKeySigner):Introduction
	worker.Hire("hired.TOMLAppKeySigner", &TOMLAppKeySigner)

}