#Protecter config file
[[Protecters]]
Name="appkey"
AuthType="hired.TOMLAppKey"
[Protecters.AuthConfig]
# Static TOML appkey.
# Example:https://github.com/herb-go/providers/blob/master/herb/statictoml/tomlappkey/example.toml 
Source="appdata/appkey.static.toml"
Example="system/exampledata/appkey.static.toml"
[Protecters.Fields]
"appid"="appidheader"
"secret"="secretheader"

[[Protecters]]
Name="appkeysecret"
AuthType="hired.TOMLAppKeySigner"
[Protecters.AuthConfig]
# Static TOML appkey.
# Example:https://github.com/herb-go/providers/blob/master/herb/statictoml/tomlappkey/example.toml 
Source="appdata/appkey.static.toml"
Hash="md5"
TimeOffsetMaxInSecond=600
[Protecters.AuthConfig.Fields]
"timestamp"="ts"
"appid"="appid"
"secret"="secret"
"path"="path"
[Protecters.Fields]
"timestamp"="timestampquery"
"sign"="signquery"
"appid"="appidquery"
"path"="path"

[[Protecters]]
Name="webupload"
AuthType="hired.TOMLAppKeySigner"
[Protecters.AuthConfig]
# Static TOML appkey.
# Example:https://github.com/herb-go/providers/blob/master/herb/statictoml/tomlappkey/example.toml 
Source="appdata/appkey.static.toml"
Hash="md5"
TimeOffsetMaxInSecond=600
[Protecters.AuthConfig.Fields]
"timestamp"="ts"
"appid"="appid"
"secret"="secret"
"object"="object"
"sizelimit"="sizelimit"
"path"="path"
[Protecters.Fields]
"timestamp"="timestampquery"
"sign"="signquery"
"appid"="appidquery"
"object"="object"
"path"="path"
"sizelimit"="sizelimit"

[[Protecters]]
Name="complete"
AuthType="hired.TOMLAppKeySigner"
[Protecters.AuthConfig]
# Static TOML appkey.
# Example:https://github.com/herb-go/providers/blob/master/herb/statictoml/tomlappkey/example.toml 
Source="appdata/appkey.static.toml"
Hash="md5"
TimeOffsetMaxInSecond=600
[Protecters.AuthConfig.Fields]
"timestamp"="ts"
"appid"="appid"
"id"="id"
"secret"="secret"
"object"="object"
"bucket"="bucket"
[Protecters.Fields]
"timestamp"="timestampquery"
"sign"="signquery"
"object"="object"
"bucket"="bucket"
"appid"="appidheader"
"id"="id"
