#Presethttpinfo config file
[[Extractors]]
Name="appidheader"
Type="header"
[Extractors.Config]
Field="appid"

[[Extractors]]
Name="secretheader"
Type="header"
[Extractors.Config]
Field="secret"

[[Extractors]]
Name="timestampquery"
Type="query"
[Extractors.Config]
Field="ts"

[[Extractors]]
Name="signquery"
Type="query"
[Extractors.Config]
Field="sign"

[[Extractors]]
Name="appidquery"
Type="query"
[Extractors.Config]
Field="appid"

[[Extractors]]
Name="namequery"
Type="query"
[Extractors.Config]
Field="name"

[[Extractors]]
Name="path"
Type="path"

[[Extractors]]
Name="object"
Type="router"
[Extractors.Config]
Field="object"

[[Extractors]]
Name="bucket"
Type="router"
[Extractors.Config]
Field="bucket"

[[Extractors]]
Name="sizelimitquery"
Type="query"
[Extractors.Config]
Field="sizelimit"

[[Extractors]]
Name="idquery"
Type="query"
[Extractors.Config]
Field="id"

[[Extractors]]
Name="basicuser"
Type="user"

[[Extractors]]
Name="basicpassword"
Type="password"

[[Fields]]
Name="appidheader"
Extractor="appidheader"

[[Fields]]
Name="secretheader"
Extractor="secretheader"

[[Fields]]
Name="timestampquery"
Extractor="timestampquery"

[[Fields]]
Name="signquery"
Extractor="signquery"

[[Fields]]
Name="appidquery"
Extractor="appidquery"

[[Fields]]
Name="path"
Extractor="path"


[[Fields]]
Name="object"
Extractor="object"

[[Fields]]
Name="bucket"
Extractor="bucket"

[[Fields]]
Name="basicuser"
Extractor="basicuser"

[[Fields]]
Name="basicpassword"
Extractor="basicpassword"

[[Fields]]
Name="sizelimit"
Extractor="sizelimitquery"

[[Fields]]
Name="id"
Extractor="idquery"