#Presethttpinfo config file
[[Extractors]]
Name="appidheader"
Type="header"
[Extractors.Config]
Field="appid"

[[Extractors]]
Name="secretheader"
Type="header"
[Extractors.Config]
Field="secret"

[[Extractors]]
Name="timestampquery"
Type="query"
[Extractors.Config]
Field="timestamp"

[[Extractors]]
Name="signquery"
Type="query"
[Extractors.Config]
Field="sign"

[[Extractors]]
Name="appidquery"
Type="query"
[Extractors.Config]
Field="appid"

[[Extractors]]
Name="namequery"
Type="query"
[Extractors.Config]
Field="name"

[[Extractors]]
Name="path"
Type="path"

[[Extractors]]
Name="bucketrouter"
Type="router"
[Extractors.Config]
Field="bucket"

[[Extractors]]
Name="bucketquery"
Type="query"
[Extractors.Config]
Field="bucket"


[[Extractors]]
Name="extlistquery"
Type="query"
[Extractors.Config]
Field="extlist"

[[Extractors]]
Name="sizelimitquery"
Type="query"
[Extractors.Config]
Field="sizelimit"

[[Extractors]]
Name="uidquery"
Type="query"
[Extractors.Config]
Field="uid"

[[Extractors]]
Name="basicuser"
Type="user"

[[Extractors]]
Name="basicpassword"
Type="password"

[[Fields]]
Name="appidheader"
Extractor="appidheader"

[[Fields]]
Name="secretheader"
Extractor="secretheader"

[[Fields]]
Name="timestampquery"
Extractor="timestampquery"

[[Fields]]
Name="signquery"
Extractor="signquery"

[[Fields]]
Name="appidquery"
Extractor="appidquery"

[[Fields]]
Name="path"
Extractor="path"

[[Fields]]
Name="bucketrouter"
Extractor="bucketrouter"

[[Fields]]
Name="bucketquery"
Extractor="bucketquery"


[[Fields]]
Name="namequery"
Extractor="namequery"


[[Fields]]
Name="uidquery"
Extractor="uidquery"

[[Fields]]
Name="basicuser"
Extractor="basicuser"

[[Fields]]
Name="basicpassword"
Extractor="basicpassword"