#Sign config file
AppidField="appid"
TimestampField="ts"
SecretField="secret"
SignField="sign"
ObjectField="object"
BucketField="bucket"
PathField="path"
SizelimitField="sizelimit"
DefaultHasher="sha256"
IDField="id"